2025-09-07 13:42:55,972 |    ERROR | clever_ai | error:128 | [ERROR_RECOVERY] Error occurred | Data: {"context": {"test": true}} | Error: Test error for recovery system
2025-09-07 13:42:55,973 |    ERROR | clever_ai | error:129 | Traceback: NoneType: None

